version: "3.9"
services:
  influxdb2:
    image: influxdb:2
    container_name: influxdb2
    volumes:
      - influxdb2-data:/var/lib/influxdb2
      - influxdb2-config:/etc/influxdb2
    ports:
      - "8086:8086"
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=${DOCKER_INFLUXDB_INIT_USERNAME}
      - DOCKER_INFLUXDB_INIT_PASSWORD=${DOCKER_INFLUXDB_INIT_PASSWORD}
      - DOCKER_INFLUXDB_INIT_ORG=${DOCKER_INFLUXDB_INIT_ORG}
      - DOCKER_INFLUXDB_INIT_BUCKET=${DOCKER_INFLUXDB_INIT_BUCKET}
      - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=${DOCKER_INFLUXDB_INIT_ADMIN_TOKEN}
    restart: always

  telegraf:
    image: telegraf:latest
    container_name: telegraf
    volumes:
      - ./telegraf:/etc/telegraf
    ports:
      - "8092:8092/udp"
      - "8094:8094/tcp"
      - "8125:8125/udp"
    depends_on:
      - influxdb2
    environment:
      - INFLUXDB_INIT_BUCKET=${DOCKER_INFLUXDB_INIT_BUCKET}
      - INFLUXDB_INIT_ORG=${DOCKER_INFLUXDB_INIT_ORG}
      - TELEGRAF_MEASUREMENT_NAME_OVERRIDE=${TELEGRAF_MEASUREMENT_NAME_OVERRIDE}
      - TELEGRAF_ENDPOINT_PATH_NAME=${TELEGRAF_ENDPOINT_PATH_NAME}
      - INFLUX_TOKEN=${DOCKER_INFLUXDB_INIT_ADMIN_TOKEN}
    restart: always

volumes:
  influxdb2-data:
  influxdb2-config:
